infra:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
      - any-glob-to-any-file: "build.gradle"

documentation:
  - changed-files:
      - any-glob-to-any-file: "*.md"
      - any-glob-to-any-file: "release-notes/**"
      - any-glob-to-any-file: "docs/**"

